

spring:

#  test:
#    database:
#      replace: none

  mvc:
    static-path-pattern: /static/**

    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


  # ===============================
  # = DATA SOURCE (MARIADB)
  # ===============================
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/board_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1q2w3e4r5t
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  # ===============================
  # = SERVLET
  # ===============================
  # Default 50MB
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 50MB

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    database: mysql
    show-sql: true
    format_sql: true

    # none, update, validate, create, create-drop
    hibernate.ddl-auto: update

    generate-ddl: false

    properties:
      hibernate:
        format-sql: true

        use_sql_comments: true

        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 1000
        jdbc.batch_size: 20
  properties:
    hibernate:
      default_batch_fetch_size: 1000
